# Generated by Django 3.0.5 on 2021-06-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='payment_Desc',
            field=models.CharField(default='Paid', max_length=200),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='payment_status',
            field=models.CharField(default='Cash', max_length=20),
        ),
    ]
