# Generated by Django 3.0.5 on 2021-06-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210604_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='tableno',
            field=models.IntegerField(default=1),
        ),
    ]
