# Generated by Django 3.0.5 on 2021-06-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210608_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tableno',
            field=models.IntegerField(default=1),
        ),
    ]
