# Generated by Django 3.0.5 on 2021-06-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tableno',
            field=models.IntegerField(blank=True),
        ),
    ]
