# Generated by Django 3.0.5 on 2021-06-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210612_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='tableno',
            new_name='table_orderno',
        ),
    ]
