# Generated by Django 3.0.5 on 2021-06-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210612_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableorders',
            old_name='tableno',
            new_name='table_orderno',
        ),
    ]
