# Generated by Django 3.0.5 on 2021-06-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210614_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imageurl',
            field=models.FileField(default='default.png', upload_to='cat_images'),
        ),
    ]
